### PR TITLE
replace getDefaultProps() with static property, move getInitialState() to componentWillMount()

### PR DESCRIPTION
**Pull request by nd0ut**

### CODE REVIEW

**Comment by brigand** [comment]
How did I not see this earlier?  You're amazing :-)

**Comment by brigand** [comment]
@nd0ut could you read over the readme?  I updated it to reflect your changes.

**Comment by nd0ut** [comment]
@brigand thanks :) yeah, readme is ok. It's time to 1.2.0 ;)

**Comment by brigand** [comment]
Done :-)

**Pull request merged**
